// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
    ElDivider: typeof import('element-plus/es')['ElDivider'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElSlider: typeof import('element-plus/es')['ElSlider'];
    ElSwitch: typeof import('element-plus/es')['ElSwitch'];
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export {}
